### ISSUE TITLE
Build failing while compiling settings.gradle

### ISSUE THREAD

**Issue by AshmitaThaparVA** [newrelic-experimental/newrelic-java-osb-11g#2]
I am trying to build this project on a Linux Machine. My gradle version is 4.10.2 and i am using java 7.
Also I dont have privileges to access internet from the machine so I am willing to build this project offline.

While I am trying to build it, its failing with compilation error.

$ /u01/gradle/gradlew extension:clean extension:install

 

FAILURE: Build failed with an exception.

 

* Where:
Settings file '/u01/newrelic_ext/newrelic-java-osb-11g-main/settings.gradle' line: 1

 

* What went wrong:
Could not compile settings file '/u01/newrelic_ext/newrelic-java-osb-11g-main/settings.gradle'.
> startup failed:
  settings file '/u01/newrelic_ext/newrelic-java-osb-11g-main/settings.gradle': 1: Only Project build scripts can contain plugins {} blocks

 

  See https://docs.gradle.org/4.10.2/userguide/plugins.html#sec:plugins_block for information on the plugins {} block

 

   @ line 1, column 1.
     plugins {
     ^

 

  1 error

 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 

* Get more help at https://help.gradle.org

 

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

 

BUILD FAILED in 0s

I require suggestions regarding following points:
1) Is this extension compatible with my version of java?
2) Is it possible to bring all dependencies offline and compile this project accordingly? What are the suggested changes for this?
3) How to fix above error?

**Comment by dhilpipre** [comment]
The build script uses the GradleGitDependencies plugin.   As is this plugin requires Gradle 6.x.   If using older versions of Gradle you will need to make a change to settings.gradle as outlined here: https://github.com/alexvasilkov/GradleGitDependenciesPlugin

If you replace the lines:

plugins {   
    id 'com.alexvasilkov.git-dependencies' version '2.0.1'
}

with 

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.alexvasilkov:gradle-git-dependencies:2.0.4'
    }
}

apply plugin: 'com.alexvasilkov.git-dependencies'

I have tested this against an earlier version of gradle and it works.

**Comment by AshmitaThaparVA** [comment]
Hi Doug,

Has this build process been tested for an offline environment? We don't have direct access to online repositories and the build keeps failing for one or another dependency while trying to resolve them. 

Hope you can share some insights on how we can achieve this.


Could not resolve all artifacts for configuration 'classpath'.
> Could not resolve com.alexvasilkov:gradle-git-dependencies:2.0.4.
  Required by:
      unspecified:unspecified:unspecified
   > Could not resolve com.alexvasilkov:gradle-git-dependencies:2.0.4.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/alexvasilkov/gradle-git-dependencies/2.0.4/gradle-git-dependencies-2.0.4.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/alexvasilkov/gradle-git-dependencies/2.0.4/gradle-git-dependencies-2.0.4.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.40.215] failed: connect timed out

 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 

* Get more help at https://help.gradle.org

**Comment by dhilpipre** [comment]
There were problems

**Comment by dhilpipre** [comment]
The build had problems related to dependencies that were being downloaded from dl.bintray.com.   This site had been shut down.   The build was corrected so it no longer requires a download from dl.bintray.com.

**Comment by A1677899900** [comment]
Hi dhilpipre .

Good day .

I tried continuing this with build ,and tested 7 extension .But we came to know below observation 
Oracle Service Bus v11g
Current version OSB 11.1.1.6  but plugins were compiled with JDK 8
jars obtained is higher version of OSB .

In order to fix it we tried 2 steps 
 we tried adding plugins in class path it failed while restarting oracle .
we tried compiling jar's to support jdk 7, javac is not found since jars built on jdk8 cant be complied to java7?

is this is version incompatibility
As per my findings 
OSB is hosted on Java 7 based environment and process is running with  1.7.0.0.jar.
 Class files built with the Java SE 8 compiler will not run on earlier releases of Java SE.

I am also aware that  no support is feasible in this case.
It will be grateful if you can advise if there is any possibilities for this .which we can try .

Regards,
AJ
